spring.application.name=Projekt

#Baza danych jako tako dziala, ale nie mozna odpalic konsoli w przegladarce (zeby obejrzec tabele itd)
#Nie wiem dlaczego tak jest moze ktos z was jest madrzejszy ode mnie.

# Konfiguracja bazy
spring.datasource.url=jdbc:h2:mem:store_everything_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Wlaczanie konsoli bazy w przegladarce - widok pod /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

